/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;
import java.awt.Component;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.DefaultButtonModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class cekout extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;
String sql;
 int jumlahPembelian;
 int totalHarga;
 String idhpp=null;
  int update;
private static String namahp;
private static int hargahp;
public static int stok;
private JSpinner spinner;
private SpinnerNumberModel spinnerModel;

    public cekout(String namahp,int hargahp,int stok) {
        this.namahp=namahp;
        this.hargahp=hargahp;
        this.stok=stok;
        initComponents();
        koneksi DB= new koneksi();
        DB.config();
       con=DB.con;
        stm=DB.stm;
       txtmerek.setText(namahp);
       jumlah();
       keterangan();
        loadtable();
        pro();
        update();
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txalamat = new javax.swing.JTextArea();
        btnhome = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmerek = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JScrollPane();
        txtket = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        spin1 = new javax.swing.JSpinner();
        idpembeli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        idhp = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbpenjualan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        datapembeli = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsimpan1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnofak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("DATA PELANGGAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Alamat :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("No hp :");

        txalamat.setColumns(20);
        txalamat.setRows(5);
        jScrollPane1.setViewportView(txalamat);

        btnhome.setBackground(new java.awt.Color(0, 204, 204));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Jumlah Pembelian :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Merek HP/id :");

        txtmerek.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Sfesifikasi");

        txtket.setEditable(false);
        txtket.setBackground(new java.awt.Color(51, 204, 255));
        txtket.setColumns(20);
        txtket.setRows(5);
        txtalamat.setViewportView(txtket);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Total :");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        idpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpembeliActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("ID pembeli :");

        idhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhpActionPerformed(evt);
            }
        });

        tbpenjualan.setBackground(new java.awt.Color(0, 51, 51));
        tbpenjualan.setForeground(new java.awt.Color(102, 255, 255));
        tbpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpenjualanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbpenjualan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datapembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Nama pembeli :");

        btnsimpan1.setBackground(new java.awt.Color(0, 204, 204));
        btnsimpan1.setText("submit");
        btnsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("No Faktur :");

        txtnofak.setBackground(new java.awt.Color(0, 102, 102));
        txtnofak.setForeground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idpembeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnohp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmerek, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idhp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(btnhome))
                                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel15)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(695, 695, 695))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnofak, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(idpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtnofak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan1)
                            .addComponent(jButton1)
                            .addComponent(btnhome)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void loadtable(){
     
        DefaultTableModel model=new DefaultTableModel();
        
         model.addColumn("no");
          model.addColumn("No Faktur");
         model.addColumn("Nama Pembeli");
        model.addColumn("ID Pembeli");
          model.addColumn("No handphone");
          model.addColumn("Alamat");
        model.addColumn("Nama HP");
        model.addColumn("Harga");
        model.addColumn("Jumlah ");
        model.addColumn("Total Bayar");
        
        try{
            int no=1;
            sql="Select nofak,namapembeli,pembeli.idpembeli,nohp,pembeli.alamatpembeli,namhp,harga,jumlahbeli,total from penjualan inner join pembeli,datahp where penjualan.idpembeli=pembeli.idpembeli and penjualan.idhp=datahp.idhp";
            rs=stm.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++, rs.getInt(1), rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getInt(7),rs.getInt(8),rs.getInt(9)});
            } 
        tbpenjualan.setModel(model);
            }catch(Exception e){
    JOptionPane.showConfirmDialog(this,e.getMessage());
     }

        
    }
  public void pro(){
        ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\datapembeli.png");
        Image icon=img.getImage();
      
       Image scale=icon.getScaledInstance( datapembeli.getWidth(),datapembeli.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon baru= new ImageIcon(scale);
      datapembeli.setIcon(baru);

   }
    private void idpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpembeliActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
menuutama1 mn=new menuutama1();
mn.setVisible(true);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void idhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
update1();
//loadtable();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan1ActionPerformed
         insert();
        simpan(); 
    }//GEN-LAST:event_btnsimpan1ActionPerformed

    private void tbpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpenjualanMouseClicked
 int baris=tbpenjualan.rowAtPoint(evt.getPoint());
 String nofak=tbpenjualan.getValueAt(baris, 1).toString();
 txtnofak.setText(nofak);
        String id=tbpenjualan.getValueAt(baris,3).toString();
        idpembeli.setText(id);
        String nama=tbpenjualan.getValueAt(baris,2).toString();
        txtnama.setText(nama);
       String nohp=tbpenjualan.getValueAt(baris,4).toString();
        txtnohp.setText(nohp);
        String alam=tbpenjualan.getValueAt(baris,5).toString();
        txalamat.setText(alam);
         String hp=tbpenjualan.getValueAt(baris,6).toString();
        txtmerek.setText(hp);
        hargahp=(int) tbpenjualan.getValueAt(baris,7);
//        txttotal.setText("");
//      int sum=(int) tbpenjualan.getValueAt(baris, 8);


 jumlahPembelian = (int) spin1.getValue();
  totalHarga = hargahp * jumlahPembelian;
txttotal.setText(String.valueOf(totalHarga));
        
 idpembeli.setEditable(false);    
 try{
     sql="SELECT idhp from penjualan where nofak='"+txtnofak.getText()+"'";
     java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
           //9 int idd=rs.getInt("idhp");
            //idhp.setText(String.valueOf(idd));
 }catch(Exception e){
       JOptionPane.showConfirmDialog(null, e.getMessage());
 } try{
     sql="SELECT harga from datahp where idhp='"+idhp.getText()+"'";
     java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
           // hargahp=rs.getInt("harga");
 }catch(Exception e){
       JOptionPane.showConfirmDialog(null, e.getMessage());
 }
    }//GEN-LAST:event_tbpenjualanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            sql="DELETE from penjualan where idpembeli='"+idpembeli.getText()+"'";
             java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            loadtable();
        }catch(Exception e){
              JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
  public void update1(){
   //Js Area=txtalamat.getViewport().getView();
      jumlahPembelian = (int) spin1.getValue();
  totalHarga = hargahp * jumlahPembelian;
txttotal.setText(String.valueOf(totalHarga));
        try{
         sql="UPDATE pembeli  SET namapembeli='"+txtnama.getText()
                 +"',alamatpembeli='"+txalamat.getText()
                 +"',nohp='"+txtnohp.getText()+"' WHERE idpembeli='"+idpembeli.getText()+"'";
       
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            loadtable();
           JOptionPane.showConfirmDialog(null, "Data berhasil di update");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
        try{
            sql="UPDATE penjualan set jumlahbeli='"+jumlahPembelian+"',total='"+totalHarga+"'where idpembeli='"+idpembeli.getText()+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            loadtable();
           //  JOptionPane.showConfirmDialog(null, "Data berhasil di update");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
  }
    public void keterangan(){
    String keterangan=null;
       try{
            sql="select keterangan from datahp where namhp='"+txtmerek.getText()+"'";
        
           rs=stm.executeQuery(sql);
           while(rs.next()){
               keterangan=rs.getString("keterangan");
               txtket.setText(keterangan);
               
           }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        } 
       try{
            sql="select idhp from datahp where namhp='"+txtmerek.getText()+"'";
        
           rs=stm.executeQuery(sql);
           while(rs.next()){
               idhpp=rs.getString("idhp");
               idhp.setText(idhpp);
           }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
}
    /**
     * @param args the command line arguments
     */
    public void simpan(){
   

    }
   
    public void jumlah(){
        int min=0;
        int max=stok;
        int langkah=1;
        
    spinnerModel=new SpinnerNumberModel(stok,min,max,langkah);
   spin1.setModel(spinnerModel);
    }
    public void insert(){
     
       jumlahPembelian = (int) spin1.getValue();
  totalHarga = hargahp * jumlahPembelian;
txttotal.setText(String.valueOf(totalHarga));
if(stok==0){
    JOptionPane.showConfirmDialog(this,"Stok Habis" );
       
    }else{
     try{
          sql="INSERT INTO pembeli values('"+idpembeli.getText()+"','"+txtnama.getText()+"','"+txalamat.getText()+"','"+txtnohp.getText()+"')";
           java.sql.PreparedStatement pst=con.prepareStatement(sql);
           pst.execute();
         loadtable();
           JOptionPane.showConfirmDialog(this, "Data berhasil disimpan");
       }catch(Exception e){
           JOptionPane.showConfirmDialog(this,e.getMessage());
       }
     try{
            sql="INSERT INTO penjualan(idpembeli,idhp,jumlahbeli,total) VALUES ('"+idpembeli.getText()+"','"+idhp.getText()+"','"+jumlahPembelian+"','"+totalHarga+"')";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
           pst.execute();
              loadtable();
        }catch(Exception e){
             JOptionPane.showConfirmDialog(this,e.getMessage());
        }
    
    }
    
}
    public void update(){
        update=stok-jumlahPembelian; 
         try{
            sql="UPDATE datahp  SET stok='"+update+"' WHERE idhp='"+idhpp+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
 }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }
    
 
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekout(namahp,hargahp,stok).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsimpan1;
    private javax.swing.JLabel datapembeli;
    private javax.swing.JTextField idhp;
    private javax.swing.JTextField idpembeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner spin1;
    private javax.swing.JTable tbpenjualan;
    private javax.swing.JTextArea txalamat;
    private javax.swing.JScrollPane txtalamat;
    private javax.swing.JTextArea txtket;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnofak;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

  
}
