/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectakhir;

import java.awt.Color;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;

String sql;
    public login() {
        initComponents();
        koneksi k =new koneksi();
        k.config();
       con=k.con;
    stm=k.stm;
//image();
//image2();
image3();
image5();
image6();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtbuat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtpas = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        aman1 = new javax.swing.JLabel();
        aman = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        utama = new javax.swing.JPanel();
        anaknya = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        anaknya2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        txtbuat.setEditable(false);
        txtbuat.setBackground(new java.awt.Color(0, 204, 204));
        txtbuat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtbuat.setForeground(new java.awt.Color(51, 51, 51));
        txtbuat.setText(" Buat akun");
        txtbuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuatMouseClicked(evt);
            }
        });
        txtbuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pasword");

        txtuser.setBackground(new java.awt.Color(0, 204, 204));
        txtuser.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 255, 255)));
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Username");

        txtpas.setBackground(new java.awt.Color(0, 204, 204));
        txtpas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 255, 255)));

        btnlogin.setBackground(new java.awt.Color(0, 204, 204));
        btnlogin.setForeground(new java.awt.Color(0, 102, 102));
        btnlogin.setText("login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new java.awt.CardLayout());

        aman1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/8201380_unlock_padlock_password_ui_lock_icon.png"))); // NOI18N
        aman1.setText("\\");

            aman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/8201356_lock_password_padlock_privacy_ui_icon.png"))); // NOI18N
            aman.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    amanMouseClicked(evt);
                }
            });

            jPanel7.setLayout(new java.awt.CardLayout());

            utama.setLayout(new java.awt.CardLayout());

            anaknya.setBackground(new java.awt.Color(0, 204, 204));
            anaknya.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    anaknyaMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout anaknyaLayout = new javax.swing.GroupLayout(anaknya);
            anaknya.setLayout(anaknyaLayout);
            anaknyaLayout.setHorizontalGroup(
                anaknyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            );
            anaknyaLayout.setVerticalGroup(
                anaknyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            utama.add(anaknya, "card2");

            anaknya2.setBackground(new java.awt.Color(0, 204, 204));

            jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel6MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout anaknya2Layout = new javax.swing.GroupLayout(anaknya2);
            anaknya2.setLayout(anaknya2Layout);
            anaknya2Layout.setHorizontalGroup(
                anaknya2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            );
            anaknya2Layout.setVerticalGroup(
                anaknya2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            utama.add(anaknya2, "card3");

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel8.setText("LOGIN");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtbuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addComponent(aman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(aman1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(193, 193, 193)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel8)
                        .addContainerGap(446, Short.MAX_VALUE)))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(txtbuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(aman1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(aman, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnlogin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)))
                            .addContainerGap(114, Short.MAX_VALUE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addContainerGap(339, Short.MAX_VALUE)))
            );

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel3.setText("WELCOME");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel3)))
                    .addGap(48, 48, 48)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        try{
            sql="Select * from login where username= '"+txtuser.getText()+"' and password='"+txtpas.getText()+"'";
            rs=stm.executeQuery(sql);
            if (rs.next()){
                if (txtuser.getText().equals(rs.getString("username"))&& txtpas.getText().equals(rs.getString("password")))
                {
                    JOptionPane.showMessageDialog(this, "Anda berhasil Login");
                    menuutama1 mn= new menuutama1();
                    mn.setVisible(true);
                    mn.setExtendedState(JFrame.MAXIMIZED_VERT);

                }
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }txtuser.setText("");
        txtpas.setText("");
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtbuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuatActionPerformed

    }//GEN-LAST:event_txtbuatActionPerformed

    private void txtbuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuatMouseClicked
           login1 lg=new login1();
       lg.setVisible(true);
       dispose();
    }//GEN-LAST:event_txtbuatMouseClicked

    private void amanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amanMouseClicked

    }//GEN-LAST:event_amanMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(anaknya);
        utama.repaint();
        utama.revalidate();

          txtpas.setEchoChar(('*'));
    }//GEN-LAST:event_jLabel6MouseClicked

    private void anaknyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anaknyaMouseClicked
       utama.removeAll();
        utama.repaint();
        utama.revalidate();

        utama.add(anaknya2);
        utama.repaint();
        utama.revalidate();
txtpas.setEchoChar((char)0);
      
    }//GEN-LAST:event_anaknyaMouseClicked

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
//        if(txtuser.getText().equals("*isikan username anda")){
//        txtuser.setText("");
//        txtuser.setForeground(new Color(0,0,0));
//    }
    }                                  

    private void txtnikFocusLost(java.awt.event.FocusEvent evt) {                                 
        
    }//GEN-LAST:event_txtuserFocusGained

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
//         if(txtuser.getText().equals("")){
//        txtuser.setText("*isikan username anda");
//         txtuser.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtuserFocusLost

      
//    public void image(){
//       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\8201356_lock_password_padlock_privacy_ui_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( aman.getWidth(),aman.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        aman.setIcon(baru);
//
////   }public void image2(){
////       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\8201380_unlock_padlock_password_ui_lock_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( aman1.getWidth(),aman1.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        aman1.setIcon(baru);
//
//   }
      
//    public void image3(){
//       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\326497_account_circle_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        jLabel4.setIcon(baru);

   // }
    public void image5(){
       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\bukalock.png");
       Image icon=img.getImage();
     
       Image scale=icon.getScaledInstance(anaknya2.getWidth(),anaknya2.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon baru= new ImageIcon(scale);
       jLabel6.setIcon(baru);
    } public void image6(){
       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\buka.png");
       Image icon=img.getImage();
     
       Image scale=icon.getScaledInstance(anaknya.getWidth(),anaknya.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon baru= new ImageIcon(scale);
       jLabel5.setIcon(baru);
    } public void image3(){
       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\326497_account_circle_icon.png");
       Image icon=img.getImage();
     
       Image scale=icon.getScaledInstance( jLabel7.getWidth(), jLabel7.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon baru= new ImageIcon(scale);
       jLabel7.setIcon(baru);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aman;
    private javax.swing.JLabel aman1;
    private javax.swing.JPanel anaknya;
    private javax.swing.JPanel anaknya2;
    private javax.swing.JToggleButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtbuat;
    private javax.swing.JPasswordField txtpas;
    private javax.swing.JTextField txtuser;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

}
